version: '3.8'

services:
  chat-server:
    build: 
      context: ./node  
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis        
      - REDIS_PASSWORD=my_password  # Change accordingly
    ports:
      - "65432:65432"                

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my_password  # Change accordingly

  